# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.get_api_scopes_response_scopes_inner import GetApiScopesResponseScopesInner

class TestGetApiScopesResponseScopesInner(unittest.TestCase):
    """GetApiScopesResponseScopesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiScopesResponseScopesInner:
        """Test GetApiScopesResponseScopesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiScopesResponseScopesInner`
        """
        model = GetApiScopesResponseScopesInner()
        if include_optional:
            return GetApiScopesResponseScopesInner(
                id = 'api_scope_01939128c3d7193ae87c4755213c07c6',
                key = 'read:logs',
                description = 'Read logs scope'
            )
        else:
            return GetApiScopesResponseScopesInner(
        )
        """

    def testGetApiScopesResponseScopesInner(self):
        """Test GetApiScopesResponseScopesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
