# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.update_role_permissions_request import UpdateRolePermissionsRequest

class TestUpdateRolePermissionsRequest(unittest.TestCase):
    """UpdateRolePermissionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateRolePermissionsRequest:
        """Test UpdateRolePermissionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateRolePermissionsRequest`
        """
        model = UpdateRolePermissionsRequest()
        if include_optional:
            return UpdateRolePermissionsRequest(
                permissions = [
                    kinde_sdk.models.update_role_permissions_request_permissions_inner.UpdateRolePermissions_request_permissions_inner(
                        id = '', 
                        operation = '', )
                    ]
            )
        else:
            return UpdateRolePermissionsRequest(
        )
        """

    def testUpdateRolePermissionsRequest(self):
        """Test UpdateRolePermissionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
