# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.api.callbacks_api import CallbacksApi


class TestCallbacksApi(unittest.TestCase):
    """CallbacksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CallbacksApi()

    def tearDown(self) -> None:
        pass

    def test_add_logout_redirect_urls(self) -> None:
        """Test case for add_logout_redirect_urls

        Add logout redirect URLs
        """
        pass

    def test_add_redirect_callback_urls(self) -> None:
        """Test case for add_redirect_callback_urls

        Add Redirect Callback URLs
        """
        pass

    def test_delete_callback_urls(self) -> None:
        """Test case for delete_callback_urls

        Delete Callback URLs
        """
        pass

    def test_delete_logout_urls(self) -> None:
        """Test case for delete_logout_urls

        Delete Logout URLs
        """
        pass

    def test_get_callback_urls(self) -> None:
        """Test case for get_callback_urls

        List Callback URLs
        """
        pass

    def test_get_logout_urls(self) -> None:
        """Test case for get_logout_urls

        List logout URLs
        """
        pass

    def test_replace_logout_redirect_urls(self) -> None:
        """Test case for replace_logout_redirect_urls

        Replace logout redirect URls
        """
        pass

    def test_replace_redirect_callback_urls(self) -> None:
        """Test case for replace_redirect_callback_urls

        Replace Redirect Callback URLs
        """
        pass


if __name__ == '__main__':
    unittest.main()
