# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.create_api_scopes_response import CreateApiScopesResponse

class TestCreateApiScopesResponse(unittest.TestCase):
    """CreateApiScopesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApiScopesResponse:
        """Test CreateApiScopesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApiScopesResponse`
        """
        model = CreateApiScopesResponse()
        if include_optional:
            return CreateApiScopesResponse(
                message = 'Success',
                code = 'OK',
                scope = kinde_sdk.models.create_api_scopes_response_scope.create_api_scopes_response_scope(
                    id = 'api_scope_0193ab57965aef77b2b687d0ef673713', )
            )
        else:
            return CreateApiScopesResponse(
        )
        """

    def testCreateApiScopesResponse(self):
        """Test CreateApiScopesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
