# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.create_meter_usage_record_request import CreateMeterUsageRecordRequest

class TestCreateMeterUsageRecordRequest(unittest.TestCase):
    """CreateMeterUsageRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMeterUsageRecordRequest:
        """Test CreateMeterUsageRecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMeterUsageRecordRequest`
        """
        model = CreateMeterUsageRecordRequest()
        if include_optional:
            return CreateMeterUsageRecordRequest(
                customer_agreement_id = 'agreement_0195ac80a14c2ca2cec97d026d864de0',
                billing_feature_code = 'pro_gym',
                meter_value = 'pro_gym',
                meter_usage_timestamp = '2024-11-18T13:32:03+11:00'
            )
        else:
            return CreateMeterUsageRecordRequest(
                customer_agreement_id = 'agreement_0195ac80a14c2ca2cec97d026d864de0',
                billing_feature_code = 'pro_gym',
                meter_value = 'pro_gym',
        )
        """

    def testCreateMeterUsageRecordRequest(self):
        """Test CreateMeterUsageRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
