# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.api.self_serve_portal_api import SelfServePortalApi


class TestSelfServePortalApi(unittest.TestCase):
    """SelfServePortalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SelfServePortalApi()

    def tearDown(self) -> None:
        pass

    def test_get_portal_link(self) -> None:
        """Test case for get_portal_link

        Get self-serve portal link
        """
        pass


if __name__ == '__main__':
    unittest.main()
