# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.get_webhooks_response import GetWebhooksResponse

class TestGetWebhooksResponse(unittest.TestCase):
    """GetWebhooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWebhooksResponse:
        """Test GetWebhooksResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWebhooksResponse`
        """
        model = GetWebhooksResponse()
        if include_optional:
            return GetWebhooksResponse(
                code = '',
                message = '',
                webhooks = [
                    kinde_sdk.models.webhook.webhook(
                        id = '', 
                        name = '', 
                        endpoint = '', 
                        description = '', 
                        event_types = [
                            ''
                            ], 
                        created_on = '', )
                    ]
            )
        else:
            return GetWebhooksResponse(
        )
        """

    def testGetWebhooksResponse(self):
        """Test GetWebhooksResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
