# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.api.property_categories_api import PropertyCategoriesApi


class TestPropertyCategoriesApi(unittest.TestCase):
    """PropertyCategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PropertyCategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create Category
        """
        pass

    def test_get_categories(self) -> None:
        """Test case for get_categories

        List categories
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update Category
        """
        pass


if __name__ == '__main__':
    unittest.main()
