# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.get_user_roles_response import GetUserRolesResponse

class TestGetUserRolesResponse(unittest.TestCase):
    """GetUserRolesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserRolesResponse:
        """Test GetUserRolesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserRolesResponse`
        """
        model = GetUserRolesResponse()
        if include_optional:
            return GetUserRolesResponse(
                data = kinde_sdk.models.get_user_roles_response_data.get_user_roles_response_data(
                    org_code = 'org_0195ac80a14e', 
                    roles = [
                        kinde_sdk.models.get_user_roles_response_data_roles_inner.get_user_roles_response_data_roles_inner(
                            id = 'role_0195ac80a14e8d71f42b98e75d3c61ad', 
                            name = 'Admin', 
                            key = 'admin', )
                        ], ),
                metadata = kinde_sdk.models.get_user_roles_response_metadata.get_user_roles_response_metadata(
                    has_more = False, 
                    next_page_starting_after = 'role_0195ac80a14e8d71f42b98e75d3c61ad', )
            )
        else:
            return GetUserRolesResponse(
        )
        """

    def testGetUserRolesResponse(self):
        """Test GetUserRolesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
