# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.update_organization_request import UpdateOrganizationRequest

class TestUpdateOrganizationRequest(unittest.TestCase):
    """UpdateOrganizationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrganizationRequest:
        """Test UpdateOrganizationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrganizationRequest`
        """
        model = UpdateOrganizationRequest()
        if include_optional:
            return UpdateOrganizationRequest(
                name = 'Acme Corp',
                external_id = 'some1234',
                background_color = '#fff',
                button_color = '#fff',
                button_text_color = '#fff',
                link_color = '#fff',
                background_color_dark = '#000',
                button_color_dark = '#000',
                button_text_color_dark = '#000',
                link_color_dark = '#000',
                theme_code = 'light',
                handle = 'acme_corp',
                is_allow_registrations = True,
                is_auto_join_domain_list = True,
                allowed_domains = ["https://acme.kinde.com","https://acme.com"],
                is_enable_advanced_orgs = True,
                is_enforce_mfa = True,
                sender_name = 'Acme Corp',
                sender_email = 'hello@acmecorp.com'
            )
        else:
            return UpdateOrganizationRequest(
        )
        """

    def testUpdateOrganizationRequest(self):
        """Test UpdateOrganizationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
