# coding: utf-8

"""
    Kinde Management API

     Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kinde_sdk.models.get_billing_entitlements_response import GetBillingEntitlementsResponse

class TestGetBillingEntitlementsResponse(unittest.TestCase):
    """GetBillingEntitlementsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingEntitlementsResponse:
        """Test GetBillingEntitlementsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingEntitlementsResponse`
        """
        model = GetBillingEntitlementsResponse()
        if include_optional:
            return GetBillingEntitlementsResponse(
                code = 'OK',
                message = 'Success',
                has_more = True,
                entitlements = [
                    kinde_sdk.models.get_billing_entitlements_response_entitlements_inner.get_billing_entitlements_response_entitlements_inner(
                        id = 'entitlement_0195ac80a14e8d71f42b98e75d3c61ad', 
                        fixed_charge = 35, 
                        price_name = 'Pro gym', 
                        unit_amount = 56, 
                        feature_code = 'CcdkvEXpbg6UY', 
                        feature_name = 'Pro Gym', 
                        entitlement_limit_max = 56, 
                        entitlement_limit_min = 56, )
                    ],
                plans = [
                    kinde_sdk.models.get_billing_entitlements_response_plans_inner.get_billing_entitlements_response_plans_inner(
                        code = '', 
                        subscribed_on = '2024-11-18T13:32:03+11:00', )
                    ]
            )
        else:
            return GetBillingEntitlementsResponse(
        )
        """

    def testGetBillingEntitlementsResponse(self):
        """Test GetBillingEntitlementsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
