# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import kinde_sdk
from kinde_sdk import configuration, schemas, api_client
from kinde_sdk.test.test_kinde_api_client import TestKindeApiClientAuthorizationCode

from .. import ApiTestMixin


class TestApiV1OrganizationUsers(ApiTestMixin, unittest.TestCase):
    """
    ApiV1OrganizationUsers unit test stubs
        List Organization Users  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        kinde_api_client = TestKindeApiClientAuthorizationCode()
        kinde_api_client.setUp()

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
