"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kinde_sdk
from kinde_sdk.model.user_profile import UserProfile


class TestUserProfile(unittest.TestCase):
    """UserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserProfile(self):
        """Test UserProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserProfile()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
