# coding: utf-8

# flake8: noqa

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.2.0"

# import ApiClient
from kinde_sdk.api_client import ApiClient

# import Configuration
from kinde_sdk.configuration import Configuration

# import exceptions
from kinde_sdk.exceptions import OpenApiException
from kinde_sdk.exceptions import ApiAttributeError
from kinde_sdk.exceptions import ApiTypeError
from kinde_sdk.exceptions import ApiValueError
from kinde_sdk.exceptions import ApiKeyError
from kinde_sdk.exceptions import ApiException
