# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

from kinde_sdk.paths.api_v1_applications.post import CreateApplication
from kinde_sdk.paths.api_v1_applications_application_id.delete import DeleteApplication
from kinde_sdk.paths.api_v1_applications_application_id_connections_connection_id.post import EnableConnection
from kinde_sdk.paths.api_v1_applications_application_id.get import GetApplication
from kinde_sdk.paths.api_v1_applications_application_id_connections.get import GetApplicationConnections
from kinde_sdk.paths.api_v1_applications.get import GetApplications
from kinde_sdk.paths.api_v1_applications_application_id_connections_connection_id.delete import RemoveConnection
from kinde_sdk.paths.api_v1_applications_application_id.patch import UpdateApplication


class ApplicationsApi(
    CreateApplication,
    DeleteApplication,
    EnableConnection,
    GetApplication,
    GetApplicationConnections,
    GetApplications,
    RemoveConnection,
    UpdateApplication,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
