# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

from kinde_sdk.paths.api_v1_feature_flags.post import CreateFeatureFlag
from kinde_sdk.paths.api_v1_feature_flags_feature_flag_key.delete import DeleteFeatureFlag
from kinde_sdk.paths.api_v1_feature_flags_feature_flag_key.put import UpdateFeatureFlag


class FeatureFlagsApi(
    CreateFeatureFlag,
    DeleteFeatureFlag,
    UpdateFeatureFlag,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
