# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

from kinde_sdk.paths.api_v1_property_categories.post import CreateCategory
from kinde_sdk.paths.api_v1_property_categories.get import GetCategories
from kinde_sdk.paths.api_v1_property_categories_category_id.put import UpdateCategory


class PropertyCategoriesApi(
    CreateCategory,
    GetCategories,
    UpdateCategory,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
