# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

from kinde_sdk.paths.api_v1_properties.post import CreateProperty
from kinde_sdk.paths.api_v1_properties_property_id.delete import DeleteProperty
from kinde_sdk.paths.api_v1_properties.get import GetProperties
from kinde_sdk.paths.api_v1_properties_property_id.put import UpdateProperty


class PropertiesApi(
    CreateProperty,
    DeleteProperty,
    GetProperties,
    UpdateProperty,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
