# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

from kinde_sdk.paths.api_v1_roles.post import CreateRole
from kinde_sdk.paths.api_v1_roles_role_id.delete import DeleteRole
from kinde_sdk.paths.api_v1_roles_role_id_permissions.get import GetRolePermission
from kinde_sdk.paths.api_v1_roles.get import GetRoles
from kinde_sdk.paths.api_v1_roles_role_id_permissions_permission_id.delete import RemoveRolePermission
from kinde_sdk.paths.api_v1_roles_role_id_permissions.patch import UpdateRolePermissions
from kinde_sdk.paths.api_v1_roles_role_id.patch import UpdateRoles


class RolesApi(
    CreateRole,
    DeleteRole,
    GetRolePermission,
    GetRoles,
    RemoveRolePermission,
    UpdateRolePermissions,
    UpdateRoles,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
