# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

from kinde_sdk.paths.api_v1_organization_users.post import AddOrganizationUsers
from kinde_sdk.paths.api_v1_user.post import CreateUser
from kinde_sdk.paths.api_v1_user.delete import Deleteuser
from kinde_sdk.paths.api_v1_organization_users.get import GetOrganizationUsers
from kinde_sdk.paths.api_v1_user.get import GetUserData
from kinde_sdk.paths.api_v1_users.get import GetUsers
from kinde_sdk.paths.api_v1_organization_users.patch import RemoveOrganizationUsers
from kinde_sdk.paths.api_v1_user.patch import UpdateUser


class UsersApi(
    AddOrganizationUsers,
    CreateUser,
    Deleteuser,
    GetOrganizationUsers,
    GetUserData,
    GetUsers,
    RemoveOrganizationUsers,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
