# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import kinde_sdk
from kinde_sdk.model.create_user_response import CreateUserResponse
from kinde_sdk import schemas


class TestCreateUserResponse(unittest.TestCase):
    """CreateUserResponse unit test stubs"""
    
    def test_create_user_response(self):
        inst = CreateUserResponse({})
        with self.assertRaises(KeyError):
            inst["id"]
        assert inst.get_item_oapg("id") is schemas.unset
        with self.assertRaises(AttributeError):
            inst.id

        inst = CreateUserResponse(id="")
        id = inst["id"]
        assert id == ""


if __name__ == '__main__':
    unittest.main()
