# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import kinde_sdk
from kinde_sdk.model.user_profile_v2 import UserProfileV2
from kinde_sdk import configuration


class TestUserProfileV2(unittest.TestCase):
    """UserProfileV2 unit test stubs"""

    _configuration = configuration.Configuration()


if __name__ == "__main__":
    unittest.main()
