# coding: utf-8

"""
    Kinde Management API

    Provides endpoints to manage your Kinde Businesses  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@kinde.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import kinde_sdk
from kinde_sdk.model.remove_organization_users_response import RemoveOrganizationUsersResponse
from kinde_sdk import schemas


class TestRemoveOrganizationUsersResponse(unittest.TestCase):
    """RemoveOrganizationUsersResponse unit test stubs"""

    def test_remove_organization_users_response(self):
        inst = RemoveOrganizationUsersResponse({})
        with self.assertRaises(KeyError):
            inst["message"]
        assert inst.get_item_oapg("message") is schemas.unset
        with self.assertRaises(AttributeError):
            inst.message

        inst = RemoveOrganizationUsersResponse(message="success")
        message = inst["message"]
        assert message == "success"


if __name__ == '__main__':
    unittest.main()
